spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/xiroadb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:xiroa}
    password: ${DB_PASSWORD:xiroa}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
